data:
  train_path: /home/kunato/language-model-agents/inst_clean_v3_train.txt
  test_path: /home/kunato/language-model-agents/inst_clean_v3_test.txt
  
training_args:
  fp16: True
  num_train_epochs: 1
  eval_steps: 200
  save_steps: 1000
  gradient_accumulation_steps: 2
  per_device_train_batch_size: 32
  warmup_steps: 5


model_name: EleutherAI/pythia-160m

gpus: 1

lr: 6e-6
