data:
  train_path: /home/kunato/language-model-agents/inst_clean_v3_train.txt
  test_path: /home/kunato/language-model-agents/inst_clean_v3_test.txt
  config:
    split_kw: 'Rosey:'

training_args:
  bf16: True
  num_train_epochs: 1
  eval_steps: 200
  save_steps: 1000
  gradient_accumulation_steps: 1
  per_device_train_batch_size: 16
  warmup_steps: 5
  deepspeed: 'config/ds_b16_config.json' # need to run using deepspeed


model_name: /home/kunato/instruct-transformer/pretrained/mt5_lm
tokenizer_name: google/mt5-large

gpus: 1

lr: 6e-6
